version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

    # Prevent Dependabot from opening a PR for torch 2.8.0
    ignore:
      - dependency-name: "torch"
        versions:
          - "2.8.0"
