FROM quay.io/pypa/manylinux_2_28_x86_64

# Install base dev tools and GCC (GCC 13 is default in this image)
RUN yum update -y && \
    yum install -y gcc gcc-c++ make wget curl yum-utils

# Install CUDA 12.6 (compatible with RHEL 8 / AlmaLinux 8)
RUN yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo && \
    yum clean all && \
    yum -y install \
        cuda-toolkit-12-6 \
        cuda-nvcc-12-6 && \
    yum clean all

# Set environment variables so PyTorch and nvcc can find CUDA
ENV CUDA_HOME=/usr/local/cuda-12.6
ENV PATH=$CUDA_HOME/bin:$PATH
ENV LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH