name: vxm
channels:
  - defaults
dependencies:
  - python==3.11
  - setuptools
  - pip
  - loguru
  - pip:
      - matplotlib
      - mrcfile
      - numpy==1.*
      - scikit-learn
      - scipy
      - tensorboard
      - torch==2.2.*
      - torchvision
      - alive_progress