[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "pybind11",
    "torch==2.6.0",
    "torchvision==0.21.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "Voxelium"
dynamic = ["version"]
description = "Voxelium - a powerful tool for volumetric CryoEM processing."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Dari Kimanius", email = "dari.kimanius@biohub.org" }
]
keywords = ["CryoEM", "CryoET", "Reconstruction", "ML"]

dependencies = [
    "torch==2.6.0",
    "torchvision==0.21.0",
    "loguru",
    "matplotlib",
    "mrcfile",
    "numpy==1.*",
    "scikit-learn",
    "scipy",
    "tensorboard",
    "alive_progress",
]

[tool.setuptools]
license-files = []
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["voxelium", "voxelium.*"]

[tool.setuptools.dynamic]
version = { attr = "voxelium.__version__" }

[project.optional-dependencies]
test = ["pytest"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "src/voxelium/torch_extensions/sparse3d",
    "src/voxelium/torch_extensions/inplace_topk"
]
