[build-system]
requires = [
    "setuptools >= 64", 
    "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Voxelium"
version = "0.0.1"
description = "Voxelium - a powerful tool for volumetric processing with CUDA support."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Dari Kimanius", email = "dari.kimanius@czii.org" }
]
keywords = ["CryoEM", "CryoET", "Reconstruction", "ML"]