name: Build and Release to PyPI

on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - release-test
  workflow_dispatch:

jobs:
  check_nvcc:
    runs-on: ubuntu-latest
    container:
      image: sameli/manylinux_2_34_x86_64_cuda_12.8
    steps:
      - name: Check nvcc path and version inside container
        run: |
          which nvcc
          nvcc --version

